### PR TITLE
Complex ops

### PR DESCRIPTION
**Pull request by Gentil-N**
Addition, Subtraction and Division (to f64) operations added for complex.

### CODE REVIEW

**Comment by At0micBee** [comment]
Saw the pull request, looks good! I'll merge it properly tomorrow!

**Comment by At0micBee** [comment]
I've look at it in more details, and the addition and subtraction aren't mathematically correct; the complex part of of the `f64` should be considered to be `0` (as the definition for complex is `a + ib`, the f64 is only the real `a` part). Therefore, the result of addition and subtraction for the complex part should be simply `im = rhs.im`.

The multiplication is correct mathematically, but it would be better if the modulus was computed using the `.powi(2)` as it is more optimized and readable. Secondly, there is an error in the `assert` statement in the documentation, the imaginary part is `-0.4`, not `0.4`.

If you have time to correct do it on your end it would be great, otherwise I can pull and fix in later on my end. As you wish!

And thanks for contributing, it's very appreciated!

**Comment by Gentil-N** [comment]
The addition and subtraction are corrected as well as the assert statement (silly mistake, sorry).

Then, in terms of performances, `.powi(2)` seems to be equivalent to `x * x` according to [this post](https://stackoverflow.com/questions/38799724/is-there-a-performance-difference-between-a-squared-function-and-directly-callin). But you are right, for more readability, it is better to write the first.

You're welcome ! I am working on a scientific project, so it is normal to contribute.

**Comment by At0micBee** [comment]
Thanks for link, I thought `powi` was more likely to optimized properly, but seems it is equivalent!

However you inverted the imaginary result for `Add` and `Sub`, it should be `im: rhs.im` and not `im: self`, again if you can do it on your end it'd be great, or I'll fix it later on my end.

Thanks for your quick response!

**Comment by At0micBee** [comment]
Thanks, merging!

**Pull request merged**
