### PR TITLE
Spherical Bessel functions added

### PR DESCRIPTION
**Pull request by Gentil-N**
I have added the first two kinds of spherical bessel functions (j and y). Miller's method is used with an upward reccurence (for y) and a downward reccurence (for j).
It's just a draft with no comments : the code could definitely be improved.

Note : `sj_array` - "s" for spherical - "j" for the first kind - "array" for the collection.

### CODE REVIEW

**Comment by At0micBee** [comment]
This looks like a great idea! I'll let you develop it further before merging, namely if possible:
- Comments
- Documentation and associated tests
- Adding options to return a single value rather than the array

Again thanks for contributing!

**Comment by Gentil-N** [comment]
So, I did my best for the documentation.

Also, to have a single value (that's to say only one function), we can apply a formula where J or Y are included (faster way) : [see this](https://en.wikipedia.org/wiki/Bessel_function#Spherical_Bessel_functions). However, a squared root takes part in this formula : for a complex argument 'z' (these functions are valid with C), I don't know which "positive" or "negative" value of the squared root we have to compute.

Then, I could add the spherical Hankel functions.

**Comment by At0micBee** [comment]
Yeah that approach looks good, at least it's a great first approach, given that the standard Bessel function are implemented for non-integer orders.

Concerning the square root I'm guessing it's relatively irrelevant as both solution are related by simply multiplying by negative one. I would recommend changing the `.sqrt()` function to return a unique solution (preferably this one `Self::from(a, b * sign)` from your function, as it requires two less operations to compute). Then we can use this as convention for both the square root and the Spherical Bessel functions. Thanks for implementing by the way, I completely forgot to do it!

Two things concerning the documentation:
1. From a readability standpoint, try to use scientific notation in the `assert!` statements, easy fix!
2. The tests in the documentation have to work when testing the crate with `cargo test`, so you have to import the actual module to run the `assert!` statements (check for example the documentation of the `j` function)

Thanks for the updates!

**Comment by Gentil-N** [comment]
I let you check if everything is ok but I think the module is ready to be merged.
More features could be added like Riccati-Bessel, derivative orders (by reccurence)... but, at least, we provide the minimum for the moment.

And voilà !

**Comment by At0micBee** [comment]
Just had a quick look, and it seems good, I'll check everything more in-depth over the week-end and merge monday hopefully!

This is an amazing contribution, thank you very much!

**Comment by At0micBee** [comment]
Quick question before merging: do all the tests pass?

**Comment by Gentil-N** [comment]
Yes! All tests (and particularly the bessel tests) pass!
I just updated the tests to support approximations: some results seem to be dependent on the plateform (on a computer, tests are valids and on another one, they are invalids because of few last digits).

**Comment by At0micBee** [comment]
Okay that's great, I'll merge tomorrow then.

I'll finish doing some additional documenting on my end and I'll push a new live version on crates.io!

**Pull request merged**
