### PR TITLE
integration module

### PR DESCRIPTION
**Pull request by Gentil-N**
Hi Vivien !

I wrote a draft for the integration module. The global idea is:

1. Create a `chunk_xxx` function to integrate with a certain method between two values.
2. Apply this one to `compute_fn` and `compute_dt`.

Details of these two functions:
- `compute_fn` is designed for a function already _implemented_ where we can take any value that we want: f(x) = y
- `compute_dt` is designed for a bunch of data where we can take each value separately: (x1, y1), (x2, y2), ... (xn, yn)

I don't know if I will implement other methods than `quad` & `trapez` (in 1D) however, basically, the idea is also to create routines for 2D, 3D and nD integration. Note: 1D integration = `dx`, 2D integration = `dxy`, 3D integration = `dxyz` and nD integration = `dn`. Perhaps, this naming is not really relevant... let me know.

(You can also check some functions to see if it's properly working but I am confident in the `trapez` method because I am currently using it in my other project)

### CODE REVIEW

**Comment by At0micBee** [comment]
Hello there!

Creating an integration module has been on my todo list since the beginning of the project but I never manage to find the time to to do it, so this is great! Overhaul I agree with the approach: taking the function as input is a very good idea and the ability to easily swap integration scheme is great (and add new ones). 

Concerning naming, I think it would be a better plan to create a folder called `integration`, and then add each integration dimension as a file (e.g.: `1d.rs`, `2d.rs`, etc); to avoid a single become too crowded with multiple `mods`.

Also from a practical standpoint the `x` and `y` values for the `dt` version should be input as two different slices, e.g.: `x: &[f64]` and `y: &[f64]` rather than a tuple with both of them `data: &[(f64, f64)]`. In my experience it seems more usual to have two `Vec`, one with the `x` values and one with the `y` values, which could make it more user friendly (I mean I know it's just a `.zip()`, but beginner friendly is always good).

I have been a bit busy lately, and I want to finish finalizing the `quantum` section so I'll come back and check it more in depth in the near future. Especially given that it could be used to computed more precisely some functions currently implemented!

Thanks again for contributing, this is great!

**Comment by Gentil-N** [comment]
Small update:

1. Folder created for this new module.
2. Data passed by slice added (I keep the _tuple_ equivalent: it could be useful).
3. `compute_fn` & `compute_dt` removed: because of performance issue. Each integration method can be optimized differently so it is not relevant (but possible) to keep a _global_ layout with _specializations_.
4. For 1D: Simpson method added (but not tested).
5. For 2D and upper: it seems to be really hard to implement equivalent of data provided by users (`quad_dt_xxx` for instance) because of boundaries conditions dependent on integration variable (last intergal boundaries dependent on previous integral for instance) and points distribution. However, it seems that other libraries don't implement it... At least, we can provide the _function_ equivalent (`quad_fn` for example).

Under construction...

**Comment by Gentil-N** [comment]
Hello there!

The `d1.rs` (one dimension integration) file is ready! You could check with other examples but for me, it seems to work properly. Regarding `d2.rs` and `d3.rs`, they have been tested on multiple examples: they just need some docs. I am waiting to finalize these three files to add `dn.rs`.

**Comment by At0micBee** [comment]
Hey!

Sorry for the slow reply, I've been busy with work so I've been looking from the side.

I just checked the files and it's starting to look pretty good indeed! I'm going to be very busy next week, so I'll wait until it's all finalized to run some tests on my side. From what I've seen it looks pretty close to being done, given that it's just mostly missing documentation.

The only think I noticed that could be improved (and maybe you've already done it, but it could help):
- The chunk functions could probably use the `#[inline(always)]` attribute, due to the frequent calls (I'm never sure the whether the compiler does it or not...)
- The `assert!` statement in the integration functions themselves could have an error message, to help the user (and typing this now I realize I think I forgot to do it for the polynomials so I'll do that also)

Great work, thanks! =)

**Pull request merged**
